FROM node:lts-bullseye-slim

ARG GID
ARG UID
ARG UNAME

ENV GID=${GID}
ENV UID=${UID}
ENV UNAME=${UNAME}

RUN mkdir /home/$UNAME

RUN groupadd -g $GID $UNAME
RUN useradd -r -u $UID -g $UNAME -d /home/$UNAME $UNAME
RUN chown $UNAME:$UNAME /home/$UNAME
