FROM node:lts-bullseye-slim

ARG GID
ARG UID
ARG UNAME

ENV GID=${GID}
ENV UID=${UID}
ENV UNAME=${UNAME}

RUN mkdir /home/$UNAME; exit 0

RUN groupadd -g $GID $UNAME; exit 0
RUN useradd -r -u $UID -g $UNAME -d /home/$UNAME $UNAME; exit 0
RUN chown $UNAME:$UNAME /home/$UNAME; exit 0
